name: deploy
run-name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  run-deployment-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          publish_branch: "master"
